#' @param description [\code{character(1)}|\code{\link{OMLDataSetDescription}}]\cr
#'   Either an \code{\link{OMLDataSetDescription}} or a \code{character(1)} that describes the data. 
#'   For the latter, all other relevant information is autogenerated from the \code{\link[mlr]{Task}}.
