# FIXME: @method show \code{signature(object = "OMLTask")}: method used to show the contents of a OMLTask object.

#' @title Construct OMLTask.
#'
#' @param id [\code{integer(1)}]\cr
#'   The ID of this task. Generated by the API.
#' @param type [\code{character(1)}]\cr
#'   The task type of this task. Task types can be browsed and created on the OpenML website.
#' @param target.features [\code{character}]\cr
#'   The name(s) of the target feature(s). There may be none, one or multiple target features.
#' @param tags [\code{character}]\cr Optional tags describing the (data of the) task.
#' @param pars [\code{list}]\cr
#'   A set of parameters specific to the task type.
#' @param data.desc.id [\code{integer(1)}]\cr
#'   The OpenML ID of the data set associated with the task.
#' @param data.set [\code{\link{OMLDataSet}}]\cr
#'   The data set including its description.
#' @param estimation.procedure [\code{\link{OMLEstimationProcedure}}]\cr
#'   Information on the task's estimation method and the asoociated data splits. Optional.
#' @param preds [\code{list}]\cr
#'   A list that contains information on the format of the predictions for the particular task.
#' @param evaluation.measures [\code{character}]\cr
#'   The evaluation measure(s) that should be used for optimization.
#' @export
#' @aliases OMLTask
#' @seealso \code{\link{OMLDataSetDescription}}
makeOMLTask = function(id, type, target.features = NA_character_, tags = NA_character_, pars = list(),
  data.desc.id, data.set = NULL, estimation.procedure, preds = list(), evaluation.measures) {

  assertInt(id)
  assertString(type)
  assertCharacter(target.features)
  assertCharacter(tags, all.missing = TRUE)
  assertList(pars)
  assertInt(data.desc.id)
  if (!is.null(data.set))
    assertClass(data.set, "OMLDataSet")
  if (!is.null(estimation.procedure))
    assertClass(estimation.procedure, "OMLEstimationProcedure")
  assertList(preds)
  assertCharacter(evaluation.measures)

  makeS3Obj("OMLTask",
    id = id, type = type, target.features = target.features, tags = tags, pars = pars,
    data.desc.id = data.desc.id, data.set = data.set, estimation.procedure = estimation.procedure,
    preds = preds, evaluation.measures = evaluation.measures
  )
}


# ***** Methods *****

# show
#' @export
print.OMLTask = function(x, ...) {
  catNotNA = function(s, val, fun = identity, ...) {
    if (!all(is.na(val)))
      catf("%s %s", s, fun(val, ...))
  }

  catf('\nOpenML Task %i :: (Data ID = %i)', x$id, x$data.desc.id)
  catNotNA('\tTask Type            :', x$type)
      catf('\tData Set             : %s :: (Version = %s, OpenML ID = %i)', x$data.set$desc$name,
       x$data.set$desc$version, x$data.set$desc$id)
  catNotNA('\tTarget Feature(s)    :', x$target.features, fun = collapse, sep = ", ")
  catNotNA('\tTags                 :', x$tags, fun = collapse, sep = ", ")
  if (!is.na(x$estimation.procedure$type)) {
    est.type = x$estimation.procedure$type
    strat = x$estimation.procedure$parameters$stratified_sampling
    strat = ifelse(!is.null(strat) && as.logical(strat), "Stratified ", "")
    n.rep = x$estimation.procedure$parameters$number_repeats
    n.rep = ifelse(!is.null(n.rep), as.character(n.rep), "")
    n.folds = x$estimation.procedure$parameters$number_folds
    n.folds = ifelse(!is.null(n.folds) && !is.na(n.folds), paste(" x", n.folds, "folds"), " rep(s)")
    catf('\tEstimation Procedure : %s%s (%s%s)', strat, est.type, n.rep, n.folds)
  }
  if (!all(x$evaluation.measures == ""))
    catNotNA('\tEvaluation Measure(s):', x$evaluation.measures, fun = collapse, sep = ", ")
}
