#' @title Construct OpenMLImplementation.
#'
#' @param id [\code{integer(1)}]\cr
#'   ID of the implementation. Generated by the server, based on name and version of the implementation.
#'   Ignored when uploaded manually.
#' @param uploader [\code{integer(1)}]\cr
#'   The user that uploaded the implementation. Added by the server. Ignored when uploaded manually.
#' @param name [\code{character(1)}]\cr
#'   The name of the implementation. Name-version combinations should be unique.\cr 
#'   Allowed characters: () [] a-z A-Z 0-9 . _ - +
#' @param version [\code{character(1)}]\cr
#'   The version of the implementation. Default is 1.0. Ignored at upload time.
#' @param external.version [\code{character(1)}]\cr
#'   An external version, defined by the user. In combination with the name, it must be unique.
#' @param description [\code{character(1)}]\cr
#'   A user description of the implementation.
#' @param creator [\code{character}]\cr
#'   Optional. The persons/institutions that created the implementation.
#' @param contributor [\code{character}]\cr
#'   Optional. (Minor) contributors to the workflow
#' @param upload.date [\code{character(1)}]\cr
#'   The date on which the implementation was uploaded.\cr
#'   Format YYYY-mm-ddThh:MM:SS. 
#'   Added by the server. Ignored when uploaded manually.
#' @param licence [\code{character(1)}]\cr
#'   Optional. Default is none, meaning Public Domain or "don't know/care".
#' @param language [\code{character(1)}]\cr
#'   Optional. Starts with one upper case letter, rest is lower case. Default is English.
#' @param full.description [\code{character(1)}]\cr
#'   Optional. Full description of the workflow, e.g, man pages filled in by tool. 
#'   This is a much more elaborate description than given in the 'description field'. It may include
#'   information about all components of the workflow.
#' @param installation.notes [\code{character(1)}]\cr
#'   Optional. Additional hints on how to run the implementation.
#' @param dependencies [\code{character(1)}]\cr
#'   Optional. The dependencies of the implementation.
#' @param bibliographical.reference [\code{list}]\cr
#'   An optional list containing information on bibliographical references in form of
#'   \code{\link{OpenMLBibRef}s}.
#' @param parameter [\code{list}]\cr
#'   The parameters of the implementation. A list containing 
#'   \code{\link{OpenMLImplementationParameter}s}.
#' @param components [\code{list}]\cr
#'   A list containing \code{\link{OpenMLImplementation}s}. Typically components of a workflow or 
#'   subfunctions of an algorithm (e.g. kernels). Components can have their own parameters.
#' @param source.url [\code{character(1)}]\cr
#'   URL from which the source code can be downloaded. Added by the server. Ignored when uploaded manually.
#' @param binary.url [\code{character(1)}]\cr
#'   URL from which the binary can be downloaded. Added by the server. Ignored when uploaded manually.
#' @param source.format [\code{character(1)}]\cr
#'   Format of the source file.
#' @param binary.format [\code{character(1)}]\cr
#'   Format of the binary file.
#' @param source.md5 [\code{character(1)}]\cr
#'   MD5 checksum to check if the source code was uploaded correctly.
#' @param binary.md5 [\code{character(1)}]\cr
#'   MD5 checksum to check if the binary code was uploaded correctly.
#' @export
#' @aliases OpenMLImplementation 
# @param implements [\code{character}]\cr
#   Ontological reference.
makeOpenMLImplementation = function(
  id = NA_integer_,
  uploader = NA_integer_,
  name,
  version = NA_character_,
  external.version = NA_character_,
  description,
  creator = NA_character_,
  contributor = NA_character_,
  upload.date = NA_character_,
  licence = NA_character_,
  language = "English",
  full.description = NA_character_,
  installation.notes = NA_character_,
  dependencies = NA_character_,
  bibliographical.reference = NULL,
  # implements = NA_character_,
  parameter = NULL,
  components = NULL,
  source.url = NA_character_,
  binary.url = NA_character_,
  source.format = NA_character_,
  binary.format = NA_character_,
  source.md5 = NA_character_,
  binary.md5 = NA_character_
  ) {
  
  assertInt(id, na.ok = TRUE)
  assertInt(uploader, na.ok = TRUE)
  assertString(name)
  assertString(version, na.ok = TRUE)
  assertString(external.version, na.ok = TRUE)
  assertString(description)
  assertCharacter(creator)
  assertCharacter(contributor)
  assertString(upload.date, na.ok = TRUE)
  assertString(licence, na.ok = TRUE)
  assertString(language)
  assertString(full.description, na.ok = TRUE)
  assertString(installation.notes, na.ok = TRUE)
  assertString(dependencies, na.ok = TRUE)
  if (!is.null(bibliographical.reference))
    assertList(bibliographical.reference)
  if (!is.null(parameter))
    assertList(parameter)
  if (!is.null(components))
    assertList(components)
  assertString(source.url, na.ok = TRUE)
  assertString(binary.url, na.ok = TRUE)
  assertString(source.format, na.ok = TRUE)
  assertString(binary.format, na.ok = TRUE)
  assertString(source.md5, na.ok = TRUE)
  assertString(binary.md5, na.ok = TRUE)
  
  makeS3Obj("OpenMLImplementation",
    id = id,
    uploader = uploader,
    name = name,
    version = version,
    external.version = external.version,
    description = description,
    creator = creator,
    contributor = contributor,
    upload.date = upload.date,
    licence = licence,
    language = language,
    full.description = full.description,
    installation.notes = installation.notes,
    dependencies = dependencies,
    bibliographical.reference = bibliographical.reference,
    #implements = implements,
    parameter = parameter,
    components = components,
    source.url = source.url,
    binary.url = binary.url,
    source.format = source.format,
    binary.format = binary.format,
    source.md5 = source.md5,
    binary.md5 = binary.md5  
  )
}

# ***** Methods *****

# show
#' @export
print.OpenMLImplementation = function(x, ...)  {
  catfNotNA = function(text, obj) {
    if (!all(is.na(obj)))
      catf(text, collapse(obj, sep = "; "))
  }

  ## General implementation info
  catf('\nFlow "%s" :: (Version = %s, OpenML ID = %i)', x$name, x$version, x$id)
  catfNotNA('\tExternal Version         : %s', x$external.version)
  catfNotNA('\tCreator(s)               : %s', x$creator)
  catfNotNA('\tLicence                  : %s', x$licence)
  catfNotNA('\tInstallation Notes       : %s', x$installation.notes)
  catfNotNA('\tDependencies             : %s', x$dependencies)
       catf('\tNumber of Flow Parameters: %i', length(x$parameter))
       catf('\tNumber of Flow Components: %i', length(x$components))
}
  

