# FIXME @method show \code{signature(object = "OpenMLTask")}: method used to show the contents of a OpenMLTask object. 

#' @title Construct OpenMLTask.
#'   
#' @param task.id [\code{integer(1)}]\cr
#'   The ID of this task. Generated by the API.
#' @param task.type [\code{character(1)}]\cr 
#'   The task type of this task. Task types can be browsed and created on the OpenML website.
#' @param task.pars [\code{list}]\cr 
#'   A set of parameters specific to the task type.
#' @param task.target.features [\code{character}]\cr 
#'   The name(s) of the target feature(s). There may be none, one or multiple target features.
#' @param task.data.desc.id [\code{integer(1)}]\cr 
#'   The OpenML ID of the data set associated with the task.
#' @param task.data.desc [\code{\link{OpenMLDataSetDescription}}]\cr 
#'   Information on the data set. Optional.
#' @param task.estimation.procedure [\code{\link{OpenMLEstimationProcedure}}]\cr 
#'   Information on the task's estimation method and the asoociated data splits. Optional.
#' @param task.preds [\code{list}]\cr 
#'   A list that contains information on the format of the predictions for the particular task.
#' @param task.evaluation.measures [\code{character}]\cr 
#'   The evaluation measure(s) that should be used for optimization.
#' @export
#' @aliases OpenMLTask
#' @seealso \code{\linkS4class{OpenMLDataSetDescription}}
makeOpenMLTask = function(task.id, task.type, task.pars = list(), task.target.features = NA_character_,
  task.data.desc.id, task.data.desc = NULL, task.estimation.procedure, task.preds = list(), 
  task.evaluation.measures) {
  
  assertIntegerish(task.id)
  assertString(task.type)
  assertList(task.pars)
  assertCharacter(task.target.features)
  assertIntegerish(task.data.desc.id)
  if (!is.null(task.data.desc))
    assertClass(task.data.desc, "OpenMLDataSetDescription")
  if (!is.null(task.estimation.procedure))
    assertClass(task.estimation.procedure, "OpenMLEstimationProcedure")
  assertList(task.preds)
  assertCharacter(task.evaluation.measures)
  
  makeS3Obj("OpenMLTask",
    task.id = task.id, task.type = task.type, task.pars = task.pars, 
    task.target.features = task.target.features, task.data.desc.id = task.data.desc.id, 
    task.data.desc = task.data.desc, task.estimation.procedure = task.estimation.procedure,
    task.preds = task.preds, task.evaluation.measures = task.evaluation.measures
  )
}


# ***** Methods *****

# show
# Note: The data splits and the predictions are not shown
#' @export
print.OpenMLTask = function(x, ...) {
  ## Task general info
  catf('\nTask ID ::  %i \n\nTask Type ::  %s', x$task.id, x$task.type)
  if (length(x$task.pars)) 
    cat(collapse(paste("\t", names(x$task.pars), " = ", x$task.pars), sep = "\n"))
  
  ## Target variables info
  catf('\nTask Target Feature :: %s', collapse(x$task.target.features, "\t"))
  
  ## Data set info
  if (!is.null(x$task.data.desc)) {
    catf('\nDataset ::  %s  (openML ID =  %i, version = %s)', 
      x$task.data.desc$name, x$task.data.desc$id, x$task.data.desc$version)
    catf('\tData frame with %i rows and %i columns', 
      nrow(x$task.data.desc$data.set), ncol(x$task.data.desc$data.set))
  }
  
  ## Estimation procedure info
  if (!is.null(x$task.estimation.procedure)) {
    catf('\nEstimation Procedure :: %s', x$task.estimation.procedure$type)
    catf('\tData splits for estimation %s.',
      ifelse(all(dim(x$task.estimation.procedure$data.splits) == 0), 'not available', 'available'))
    if (length(x$task.estimation.procedure$parameters)) {
      
      cat('\tParameters of the estimation procedure:\n')
      
      cat(collapse(paste("\t", names(x$task.estimation.procedure$parameters), " = ", 
        x$task.estimation.procedure$parameters), sep = "\n"))
    }
  }
  cat('\nPredictions ::\n')
  catf('\tFormat = %s', x$task.preds$format)
  cat('\tColumns:\n')
  cat(collapse(paste("\t\t", names(x$task.preds$features), " = ", x$task.preds$features), sep = "\n"))
  cat('\nEvaluation Measures ::\n')
  catf('%s', collapse(x$task.evaluation.measures, '\n'))
}

