#' @title Construct OpenMLDataSetDescription.
#'
#' @param id [\code{integer(1)}]\cr
#'    ID, autogenerated by the server.
#' @param name [\code{character(1)}]\cr
#'   The  name of the data set.
#' @param version [\code{character(1)}]\cr
#'   Version of the data set, added by the server. 
#' @param description [\code{character(1)}]\cr
#'   Description of the data set, given by the uploader.
#' @param format [\code{character(1)}]\cr
#'   Format of the data set. Typically, this is "arff".
#' @param creator [\code{character}]\cr
#'   The person(s), that created this data set. Optional.
#' @param contributor [\code{character}]\cr
#'   People, that contibuted to this version of the data set (e.g., by reformatting). Optional. 
#' @param collection.date [\code{character(1)}]\cr
#'   The date the data was originally collected. Given by the uploader. Optional.
#' @param upload.date [\code{\link[base]{POSIXt}}]\cr
#'   The date the data was uploaded. Added by the server.
#' @param language [\code{character(1)}]\cr
#'   Language in which the data is represented. Starts with 1 upper case letter, rest lower case, 
#'   e.g. 'English'
#' @param licence [\code{character(1)}]\cr   
#'   Licence of the data. \code{NA} means: Public Domain or "don't know/care".
#' @param url [\code{character(1)}]\cr 
#'   Valid URL that points to the data file.
#' @param default.target.attribute [\code{character}]\cr 
#'   The default target attribute, if it exists. Of course, tasks can be defined that use 
#'   another attribute as target.
#' @param row.id.attribute [\code{character(1)}]\cr  
#'   The attribute that represents the row-id column, if present in the data set. Else \code{NA}. 
#' @param version.label [\code{character(1)}]\cr
#'   Version label provided by user, something relevant to the user. Can also be a date, 
#'   hash, or some other type of id.
#' @param citation [\code{character(1)}]\cr
#'   Reference(s) that should be cited when building on this data.
#' @param visibility [\code{character(1)}]\cr
#'   Who can see the data set. Typical values: 'Everyone', 'All my friends', 'Only me'. 
#'   Can also be any of the user's circles.
#' @param original.data.url [\code{character(1)}]\cr
#'   For derived data, the url to the original data set. 
#'   This can be an OpenML data set, e.g. 'http://openml.org/d/1'.
#' @param paper.url [\code{character(1)}]\cr   
#'   Link to a paper describing the data set.
#' @param md5.checksum [\code{character(1)}]\cr 
#'   MD5 checksum to check if the data set is downloaded without corruption.
#' @param data.set [\code{data.frame}]\cr 
#'   The data set. 
#' @param original.col.names [\code{character}]\cr
#'   The original column names of the data set. These might not be valid names in R!
#' @param new.col.names [\code{character}]\cr
#'   New column names that are actually used in R. These are valid and unique and differ from the 
#'   original column names only if those are invalid. 
#' @export
#' @aliases OpenMLDataSetDescription OpenMLDataSetDescription-class
makeOpenMLDataSetDescription = function(id, name, version, description, format, 
  creator = NA_character_, contributor = NA_character_, collection.date = NA_character_, upload.date,
  language = NA_character_, licence = NA_character_, url, default.target.attribute = NA_character_, 
  row.id.attribute = NA_character_, version.label = NA_character_, citation = NA_character_, 
  visibility = NA_character_, original.data.url = NA_character_, paper.url = NA_character_,
  md5.checksum = NA_character_, data.set, original.col.names = NA_character_, 
  new.col.names = NA_character_) {
  
  assertInt(id)
  assertString(name)
  assertString(version)
  assertString(description)
  assertString(format)
  assertCharacter(creator)
  assertCharacter(contributor)
  assertString(collection.date, na.ok = TRUE)
  assertClass(upload.date, "POSIXt")
  assertString(language, na.ok = TRUE)
  assertString(licence, na.ok = TRUE)
  assertString(url)
  assertString(default.target.attribute, na.ok = TRUE)
  assertString(row.id.attribute, na.ok = TRUE)
  assertString(version.label, na.ok = TRUE)
  assertString(citation, na.ok = TRUE)
  assertString(visibility, na.ok = TRUE)
  assertString(original.data.url, na.ok = TRUE)
  assertString(paper.url, na.ok = TRUE)
  assertString(md5.checksum, na.ok = TRUE)
  assertDataFrame(data.set)
  assertCharacter(original.col.names)
  assertCharacter(new.col.names)
  
  makeS3Obj("OpenMLDataSetDescription",
    id = id, name = name, version = version, description = description, format = format,
    creator = creator, contributor = contributor, collection.date = collection.date, 
    upload.date = upload.date, language = language, licence = licence, url = url, 
    default.target.attribute = default.target.attribute,row.id.attribute = row.id.attribute, 
    version.label = version.label, citation = citation, visibility = visibility, 
    original.data.url = original.data.url, paper.url = paper.url, md5.checksum = md5.checksum, 
    data.set = data.set, original.col.names = original.col.names, new.col.names = new.col.names)
}

# ***** Methods *****

#' @export
print.OpenMLDataSetDescription = function(x, ...) {
  catfNotNA = function(text, obj) {
    if (!all(is.na(obj)))
      catf(text, collapse(obj, sep = "; "))
  }
  # Wrong indentation to see alignment
  catf('\nData Set "%s" :: (Version = %s, OpenML ID = %i)', x$name, x$version, x$id)
  catfNotNA('\tCollection Data         : %s', x$collection.date)
  catfNotNA('\tCreator(s)              : %s', x$creator)
  catfNotNA('\tDefault Target Attribute: %s', x$default.target.attribute)
}