# FIXME: @method show \code{signature(object = "OpenMLTask")}: method used to show the contents of a OpenMLTask object.

#' @title Construct OpenMLTask.
#'
#' @param id [\code{integer(1)}]\cr
#'   The ID of this task. Generated by the API.
#' @param type [\code{character(1)}]\cr
#'   The task type of this task. Task types can be browsed and created on the OpenML website.
#' @param pars [\code{list}]\cr
#'   A set of parameters specific to the task type.
#' @param target.features [\code{character}]\cr
#'   The name(s) of the target feature(s). There may be none, one or multiple target features.
#' @param data.desc.id [\code{integer(1)}]\cr
#'   The OpenML ID of the data set associated with the task.
#' @param data.desc [\code{\link{OpenMLDataSetDescription}}]\cr
#'   Information on the data set. Optional.
#' @param estimation.procedure [\code{\link{OpenMLEstimationProcedure}}]\cr
#'   Information on the task's estimation method and the asoociated data splits. Optional.
#' @param preds [\code{list}]\cr
#'   A list that contains information on the format of the predictions for the particular task.
#' @param evaluation.measures [\code{character}]\cr
#'   The evaluation measure(s) that should be used for optimization.
#' @export
#' @aliases OpenMLTask OpenMLTask-class
#' @seealso \code{\linkS4class{OpenMLDataSetDescription}}
makeOpenMLTask = function(id, type, pars = list(), target.features = NA_character_,
  data.desc.id, data.desc = NULL, estimation.procedure, preds = list(),
  evaluation.measures) {

  assertInt(id)
  assertString(type)
  assertList(pars)
  assertCharacter(target.features)
  assertInt(data.desc.id)
  if (!is.null(data.desc))
    assertClass(data.desc, "OpenMLDataSetDescription")
  if (!is.null(estimation.procedure))
    assertClass(estimation.procedure, "OpenMLEstimationProcedure")
  assertList(preds)
  assertCharacter(evaluation.measures)

  makeS3Obj("OpenMLTask",
    id = id, type = type, pars = pars,
    target.features = target.features, data.desc.id = data.desc.id,
    data.desc = data.desc, estimation.procedure = estimation.procedure,
    preds = preds, evaluation.measures = evaluation.measures
  )
}


# ***** Methods *****

# show
#' @export
print.OpenMLTask = function(x, ...) {
  catNotNA = function(s, val, fun = identity, ...) {
    if (!all(is.na(val))) 
      catf("%s %s", s, fun(val, ...))
  }
  
  catf('\nOpenML Task %i :: (Data ID = %i)', x$id, x$data.desc.id)
  catNotNA('\tTask Type            :', x$type)
      catf('\tData Set             : %s :: (Version %s, OpenML ID = %i)', x$data.desc$name, 
       x$data.desc$version, x$data.desc$id)
  catNotNA('\tTarget Feature(s)    :', x$target.features, fun = collapse, sep = ", ")
  if (!is.na(x$estimation.procedure$type)) {
    est.type = x$estimation.procedure$type
    strat = x$estimation.procedure$parameters$stratified_sampling
    strat = ifelse(!is.null(strat) && as.logical(strat), "Stratified ", "")
    n.rep = x$estimation.procedure$parameters$number_repeats
    n.rep = ifelse(!is.null(n.rep), paste(n.rep, "x "), "") 
    n.folds = x$estimation.procedure$parameters$number_folds
    n.folds = ifelse(!is.null(n.folds), paste(n.folds, "folds"), "") 
    catf('\tEstimation Procedure : %s%s (%s%s)', strat, est.type, n.rep, n.folds)
  }
  if (!all(x$evaluation.measures == ""))
    catNotNA('\tEvaluation Measure(s):', x$evaluation.measures, fun = collapse, sep = ", ")
}