#' OpenMLImplementation
#'
#' This class of objects contains the information describing an OpenML implementation.
#' 
#' Objects can be created by calls of the form \code{OpenMLImplementation(...)}.
#' The objects contain information on ... .
#'
#'
#' @section Slots: 
#'  \describe{
#'    \item{\code{id}}{[\code{character}]\cr
#'    ID of the implementation. Generated by the server, based on name and version of the implementation.
#'    Ignored when uploaded manually.}
#'    \item{\code{uploader}}{[\code{integer}]\cr
#'    The user that uploaded the implementation. Added by the server. Ignored when uploaded manually.}
#'    \item{\code{name}}{[\code{character}]\cr
#'    The name of the implementation. Name-version combinations should be unique.\cr 
#'    Allowed characters: () [] a-z A-Z 0-9 . _ - +}
#'    \item{\code{version}}{[\code{character}]\cr
#'    The version of the implementation.\cr 
#'    Allowed characters: () [] a-z A-Z 0-9 . _ - +}
#'    \item{\code{description}}{[\code{character}]\cr
#'    A user description of the implementation.}
#'    \item{\code{creator}}{[\code{character}]\cr
#'    Optional. The persons/institutions that created the implementation.}
#'    \item{\code{contributor}}{[\code{character}]\cr
#'    Optional. (Minor) contributors to the workflow}
#'    \item{\code{upload.date}}{[\code{character}]\cr
#'    The date on which the implementation was uploaded.\cr
#'    Format YYYY-mm-ddThh:MM:SS. 
#'    Added by the server. Ignored when uploaded manually.}
#'    \item{\code{licence}}{[\code{character}]\cr
#'    Optional. Default is none, meaning Public Domain or "don't know/care".}
#'    \item{\code{language}}{[\code{character}]\cr
#'    Optional. Starts with one upper case letter, rest is lower case. Default is English.}
#'    \item{\code{full.description}}{[\code{character}]\cr
#'    Optional. Full description of the workflow, e.g, man pages filled in by tool. 
#'    This is a much more elaborate description than given in the 'description field'. It may include
#'    information about all components of the workflow.}
#'    \item{\code{installation.notes}}{[\code{character}]\cr
#'    Installation notes.}
#'    \item{\code{dependencies}}{[\code{character}]\cr
#'    The dependencies of the implementation.}
#'    \item{\code{bibliographical.reference}}{[\code{list}]\cr
#'    An optional list containing information on bibliographical references in form of
#'    \code{\link{OpenMLBibRef}s}.}
#'    %\item{\code{implements}}{[\code{character}]\cr
#'    %Ontological reference.}
#'    \item{\code{parameter}}{[\code{list}]\cr
#'    The parameters of the implementation. A list containing 
#'    \code{\link{OpenMLImplementationParameter}s}.}
#'    \item{\code{components}}{[\code{list}]\cr
#'    A list contatining \code{\link{OpenMLImplementation}s}. Typically components of a workflow or 
#'    subfunctions of an algorithm (e.g. kernels). Components can have their own parameters.}
#'    \item{\code{source.url}}{[\code{character}]\cr
#'    URL from which the source code can be downloaded. Added by the server. Ignored when uploaded manually.}
#'    \item{\code{binary.url}}{[\code{character}]\cr
#'    URL from which the binary can be downloaded. Added by the server. Ignored when uploaded manually.}
#'    \item{\code{source.format}}{[\code{character}]\cr
#'    Format of the source file.}
#'    \item{\code{binary.format}}{[\code{character}]\cr
#'    Format of the binary file.} 
#'    \item{\code{source.md5}}{[\code{character}]\cr
#'    MD5 checksum to check if the source code was uploaded correctly.}
#'    \item{\code{binary.md5}}{[\code{character}]\cr
#'    MD5 checksum to check if the binary code was uploaded correctly.}
#'  }
#'
#' @name OpenMLImplementation
#' @rdname OpenMLImplementation
#' @aliases OpenMLImplementation-class
#' @exportClass OpenMLImplementation

# --------------------------------------------------------------
# class def
setClass("OpenMLImplementation", representation(
  id = "character",
  uploader = "integer",
  name = "character",
  version = "character",
  external.version = 'character',
  description = "character",
  creator = "character",
  contributor = "character",
  upload.date = "character",
  licence = "character",
  language = "character",
  full.description = "character",
  installation.notes = "character",
  dependencies = "character",
  #FIXME add implements
  bibliographical.reference = "list",
  #implements = "character",
  parameter = "list",
  components = "list",
  source.url = "character",
  binary.url = "character",
  source.format = "character",
  binary.format = "character",
  source.md5 = "character",
  binary.md5 = "character"
  
#  programming.language = "character",
#  operating.system = "character",
#  bib.url = "character",
#  implements = "character",
))


# --------------------------------------------------------------
# constructor function
OpenMLImplementation = function(
  id = character(0L),
  uploader = integer(),
  name = character(0L),
  version = character(0L),
  external.version = character(0L),
  description = character(0L),
  creator = character(0L),
  contributor = character(0L),
  upload.date = character(0L),
  licence = character(0L),
  language = "English",
  full.description = character(0L),
  installation.notes = character(0L),
  dependencies = character(0L),
  bibliographical.reference = list(),
  # implements = character(0L),
  parameter = list(),
  components = list(),
  source.url = character(0L),
  binary.url = character(0L),
  source.format = character(0L),
  binary.format = character(0L),
  source.md5 = character(0L),
  binary.md5 = character(0L)
) {
  makeS3Obj("OpenMLImplementation",
    id = id,
    uploader = uploader,
    name = name,
    version = version,
    external.version = external.version,
    description = description,
    creator = creator,
    contributor = contributor,
    upload.date = upload.date,
    licence = licence,
    language = language,
    full.description = full.description,
    installation.notes = installation.notes,
    dependencies = dependencies,
    bibliographical.reference = bibliographical.reference,
    #implements = implements,
    parameter = parameter,
    components = components,
    source.url = source.url,
    binary.url = binary.url,
    source.format = source.format,
    binary.format = binary.format,
    source.md5 = source.md5,
    binary.md5 = binary.md5  
  )
}

# ***** Methods *****

# show
#' @export
print.OpenMLImplementation = function(x, ...)  {
  catNotEmpty = function(s, val) {
    if (val != "" && length(val) > 0) 
      catf("%s %s", s, val)
  }
  
  ## General implementation info
  catf('\n** Implementation Information **')
  
  catNotEmpty('ID               :: ', x$id)
  catNotEmpty('Name             :: ', x$name)
  catNotEmpty('OpenML Version   :: ', x$version)
  catNotEmpty('External Version :: ', x$external.version)
  
  ## Authors and contributors
  if (length(x$creator) > 0) {
    cat('\nCreator(s)     :: ')
    cat(collapse(x$creator, sep = ", "))
  }
  if (length(x$contributor) > 0) {
    cat('\nContributor(s) :: ')
    cat(collapse(x$contributor, sep = ", "))
  }
  
  ## Other info
  catf('\nDate :: %s', x$upload.date)
  #catNotEmpty('Licence :: ', x$licence)
  #catNotEmpty('Language :: ', x$language)
  
  ## Implementation specific info
  catf('\n\nDescription of the implementation :')
  catf(x$description)
  
  #FIXME: We need to reimplement these lines.
  #catNotEmpty('Full description :: ', x$full.description)
  #catNotEmpty('Installation notes :: ', x$installation.notes)
  #catNotEmpty('Dependencies :: ', collapse(x$dependencies, ", "))
  #catNotEmpty('\nProgramming language :: ',x$programming.language)
  #catNotEmpty('\nOperating system :: ',x$operating.system)
  
  ## Bibliographic info
  #if (x$bib.citation != "")
  #  catf('\nBibliographic citation :: ',x$bib.citation)
  #if (x$bib.url != "")
  #  catf('\nBibliographic URL :: ',x$bib.url)
  
  ## More implementation details
  #if (x$implements != "")
  #  catf('\nImplements :: ',x$implements)
 
  ## Implementation parameters
  if (length(x$parameter)) {
    catf('\nImplementation parameters :\n')
    for(i in 1:length(x$parameter)) 
      print(x$parameter[i])
  }
  
  ## Implementation components
  if (length(x$components)) {
    catf('\nDescription of Implementation Components ::')
    print(x$components)
  }
  
  ## Bibliographical references
  if (length(x$bibliographical.reference) > 0) {
    catf("Bibliographical Reference(s):")
    for(i in 1:length(x$bibliographical.reference)) 
      print(x$bibliographical.reference[[i]])  
  }
  ## The implementation source information
  #catNotEmpty('Source URL :: ', x$source.url)
  #catNotEmpty('Binary URL :: ', x$binary.url)
  #catNotEmpty('Source format :: ', x$source.format)
  #catNotEmpty('Binary format :: ', x$binary.format)
  #catNotEmpty('Source MD5 :: ', x$source.md5)
  #catNotEmpty('Binary MD5 :: ', x$binary.md5)
  #cat('\n\n')
}
  

