# FIXME: @method show \code{signature(object = "OpenMLTask")}: method used to show the contents of a OpenMLTask object.

#' @title Construct OpenMLTask.
#'
#' @param id [\code{integer(1)}]\cr
#'   The ID of this task. Generated by the API.
#' @param type [\code{character(1)}]\cr
#'   The task type of this task. Task types can be browsed and created on the OpenML website.
#' @param pars [\code{list}]\cr
#'   A set of parameters specific to the task type.
#' @param target.features [\code{character}]\cr
#'   The name(s) of the target feature(s). There may be none, one or multiple target features.
#' @param data.desc.id [\code{integer(1)}]\cr
#'   The OpenML ID of the data set associated with the task.
#' @param data.desc [\code{\link{OpenMLDataSetDescription}}]\cr
#'   Information on the data set. Optional.
#' @param estimation.procedure [\code{\link{OpenMLEstimationProcedure}}]\cr
#'   Information on the task's estimation method and the asoociated data splits. Optional.
#' @param preds [\code{list}]\cr
#'   A list that contains information on the format of the predictions for the particular task.
#' @param evaluation.measures [\code{character}]\cr
#'   The evaluation measure(s) that should be used for optimization.
#' @export
#' @aliases OpenMLTask
#' @seealso \code{\linkS4class{OpenMLDataSetDescription}}
makeOpenMLTask = function(id, type, pars = list(), target.features = NA_character_,
  data.desc.id, data.desc = NULL, estimation.procedure, preds = list(),
  evaluation.measures) {

  assertIntegerish(id)
  assertString(type)
  assertList(pars)
  assertCharacter(target.features)
  assertIntegerish(data.desc.id)
  if (!is.null(data.desc))
    assertClass(data.desc, "OpenMLDataSetDescription")
  if (!is.null(estimation.procedure))
    assertClass(estimation.procedure, "OpenMLEstimationProcedure")
  assertList(preds)
  assertCharacter(evaluation.measures)

  makeS3Obj("OpenMLTask",
    id = id, type = type, pars = pars,
    target.features = target.features, data.desc.id = data.desc.id,
    data.desc = data.desc, estimation.procedure = estimation.procedure,
    preds = preds, evaluation.measures = evaluation.measures
  )
}


# ***** Methods *****

# show
# Note: The data splits and the predictions are not shown
#' @export
print.OpenMLTask = function(x, ...) {
  ## Task general info
  catf('\nTask ID ::  %i \n\nTask Type ::  %s', x$id, x$type)
  if (length(x$pars))
    cat(collapse(paste("\t", names(x$pars), " = ", x$pars), sep = "\n"))

  ## Target variables info
  catf('\nTask Target Feature :: %s', collapse(x$target.features, "\t"))

  ## Data set info
  if (!is.null(x$data.desc)) {
    catf('\nDataset ::  %s  (openML ID =  %i, version = %s)',
      x$data.desc$name, x$data.desc$id, x$data.desc$version)
    catf('\tData frame with %i rows and %i columns',
      nrow(x$data.desc$data.set), ncol(x$data.desc$data.set))
  }

  ## Estimation procedure info
  if (!is.null(x$estimation.procedure)) {
    catf('\nEstimation Procedure :: %s', x$estimation.procedure$type)
    catf('\tData splits for estimation %s.',
      ifelse(all(dim(x$estimation.procedure$data.splits) == 0), 'not available', 'available'))
    if (length(x$estimation.procedure$parameters)) {

      cat('\tParameters of the estimation procedure:\n')

      cat(collapse(paste("\t", names(x$estimation.procedure$parameters), " = ",
        x$estimation.procedure$parameters), sep = "\n"))
    }
  }
  cat('\nPredictions ::\n')
  catf('\tFormat = %s', x$preds$format)
  cat('\tColumns:\n')
  cat(collapse(paste("\t\t", names(x$preds$features), " = ", x$preds$features), sep = "\n"))
  cat('\nEvaluation Measures ::\n')
  catf('%s', collapse(x$evaluation.measures, '\n'))
}

