#FIXME:  parse date as Date and change slot type
#FIXME:  upload.date is of class POSIXt, but collection.date is of class character
# collection.date = "character",
# upload.date = "POSIXt",

#' @title Construct OpenMLDataSetDescription.
#'
#' @param id [\code{integer(1)}]\cr
#'    ID, autogenerated by the server.
#' @param name [\code{character(1)}]\cr
#'   The  name of the data set.
#' @param version [\code{character(1)}]\cr
#'   Version of the data set, added by the server. 
#' @param description [\code{character(1)}]\cr
#'   Description of the data set, given by the uploader.
#' @param format [\code{character(1)}]\cr
#'   Format of the data set. Typically, this is "arff".
#' @param creator [\code{character}]\cr
#'   The person(s), that created this data set. Optional.
#' @param contributor [\code{character}]\cr
#'   People, that contibuted to this version of the data set (e.g., by reformatting). Optional. 
#' @param collection.date [\code{character(1)}]\cr
#'   The date the data was originally collected. Given by the uploader. Optional.
#' @param upload.date [\code{\link[base]{POSIXt}}]\cr
#'   The date the data was uploaded. Added by the server.
#' @param language [\code{character(1)}]\cr
#'   Language in which the data is represented. Starts with 1 upper case letter, rest lower case, 
#'   e.g. 'English'
#' @param licence [\code{character(1)}]\cr   
#'   Licence of the data. \code{NA} means: Public Domain or "don't know/care".
#' @param url [\code{character(1)}]\cr 
#'   Valid URL that points to the data file.
#' @param row.id.attribute [\code{character(1)}]\cr  
#'   The attribute that represents the row-id column, if present in the dataset. Else \code{NA}. 
#' @param md5.checksum [\code{character(1)}]\cr 
#'   MD5 checksum to check if the dataset is downloaded without corruption.
#' @param data.set [\code{data.frame}]\cr 
#'   The data set. 
#' @param original.col.names [\code{character}]\cr
#'   The original column names of the data set. These might not be valid names in R!
#' @param new.col.names [\code{character}]\cr
#'   New column names that are actually used in R. These are valid and unique and differ from the original
#'   column names only if those are invalid. 
#' @export
#' @aliases OpenMLDataSetDescription
makeOpenMLDataSetDescription = function(id, name, version, description, format, creator = NA_character_, 
  contributor = NA_character_, collection.date = NA_character_, upload.date,
  language = NA_character_, licence = NA_character_, url, # default.target.attribute, 
  row.id.attribute = NA_character_, md5.checksum = NA_character_,
  data.set, original.col.names = NA_character_, new.col.names = NA_character_) {
  
  assertIntegerish(id)
  assertString(name)
  assertString(version)
  assertString(description)
  assertString(format)
  assertCharacter(creator)
  assertCharacter(contributor)
  assertString(collection.date, na.ok = TRUE)
  assertClass(upload.date, "POSIXt")
  assertString(language, na.ok = TRUE)
  assertString(licence, na.ok = TRUE)
  assertString(url)
  # assertString(default.target.attribute)
  assertString(row.id.attribute, na.ok = TRUE)
  assertString(md5.checksum, na.ok = TRUE)
  assertDataFrame(data.set)
  assertCharacter(original.col.names)
  assertCharacter(new.col.names)
  
  makeS3Obj("OpenMLDataSetDescription",
    id = id, name = name, version = version, description = description, format = format,
    creator = creator, contributor = contributor, collection.date = collection.date, 
    upload.date = upload.date, language = language, licence = licence, url = url, 
    # default.target.attribute = default.target.attribute, 
    row.id.attribute = row.id.attribute, md5.checksum = md5.checksum, data.set = data.set, 
    original.col.names = original.col.names, new.col.names = new.col.names)
}

# ***** Methods *****

#' @export
print.OpenMLDataSetDescription = function(x, ...) {
  # incorrect indentation to see aligment!
  catf('\nDataset %s :: (openML ID = %i, version = %s)', x$name, x$id, x$version)
  catf('\tCreator          : %s', x$creator)
  if (length(x$contributor) > 0)
    catf('\tContributor      : %s', x$contributor)
  catf('\tCollection Date  : %s', x$collection.date)
  catf('\tUpload Date      : %s', x$upload.date)
  if (x$licence != '')
    catf('\tLicence          : %s', x$licence)
  catf('\tURL              : %s', x$url)
  if (x$language != '')
    catf('\tLanguage         : %s', x$language)
  catf('\tFormat           : %s', x$format)
  if (x$row.id.attribute != '')
    catf('\tRow Id Attr.  	 : %s', x$row.id.attribute)
  if (x$md5.checksum != '')
    catf('\tmd5 Check Sum    : %s', x$md5.checksum)
  catf('\tDescription :')
  cat(collapse(paste('\t\t', strwrap(x$description), '\n'), sep=''))
  cat('\n')
  catf('\tData :')
  catf(printStrToChar(x$data.set))
}

